- name: Install nginx
  package:
    name: nginx
    state: latest

- name: Replace nginx config
  template:
        src=templates/nginx.conf
        dest=/etc/nginx/nginx.conf

- name: Install PHP 7.2
  package:
    name: php72
    state: latest

- name: Install PHP-FPM
  package:
    name: php72-fpm
    state: latest

- name: Get PHPINFO
  shell: php -r "phpinfo();" > phpinfo
